name : node.js ci pipeline
 on :
    push :
    branches : [main]
    pull-request :
      branches : [main]

Jobs :
  build and test :
    runs-on : ubuntu-latest
    steps :
      -name : set up node.js
       uses : actions/checkout@v4

       -name : install dependencies
        run  : npm ci

         name : run test
          run : npm test
    
